### ISSUE TITLE
Unable to find local instance upgrade instructions

### ISSUE THREAD

**Issue by marnovdm** [taigaio/taiga-doc#103]
I'm running a local taiga instance based on taiga-web-dist and taiga-back repo's with the stable branch. Can I just do a 'git pull' on both directories, restart services and be good to go? I expect some python manage.py migrate or something is required? From the documentation for installation @ http://taigaio.github.io/taiga-doc/dist/setup-production.html I found these steps:

python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py loaddata initial_role
python manage.py compilemessages
python manage.py collectstatic --noinput

I'd assume the following would perhaps be enough after a git pull, but would like someone to confirm.

python manage.py migrate --noinput
python manage.py compilemessages
python manage.py collectstatic --noinput

A simple upgrade script could be:

#!/bin/bash
cd /opt/taiga/front/
git pull
cd /opt/taiga/back
git pull
pip install -r /opt/taiga/back/requirements.txt
python manage.py migrate --noinput
python manage.py compilemessages
python manage.py collectstatic --noinput
/etc/init.d/gunicorn restart

Missed anything?

Thanks in advance, really enjoy using your issue tracker after using Jira for a while :+1:

**Comment by bameda** [comment]
Hi @marnovdm  the information is here
http://taigaio.github.io/taiga-doc/dist/setup-faqs.html#faq-maintain-update

**Comment by marnovdm** [comment]
Thanks @bameda, can't believe I missed that, sorry!

**Comment by bameda** [comment]
The truth is that this section is hidden, we are going to create a new one in the index page about the upgrade proccess.

**Comment by marnovdm** [comment]
Ah that makes me feel a bit better about bothering you guys about this! I think that would help a lot of users upgrading their local instances, as I was unable to find instructions elsewhere. Thanks again!

**Comment by bameda** [comment]
Totally agree. Thanks for your comments :dancer:
