### ISSUE TITLE
Change in taiga-front config

### ISSUE THREAD

**Issue by richbl** [taigaio/taiga-doc#114]
DOES:
On https://taigaio.github.io/taiga-doc/dist/setup-development.html, in section **4.1.2. NodeJS and friends**, subsection **Download the code**, there's reference to a /dist folder. However, it appears that current taiga-front drops now use a /conf folder.

SHOULD:
Change documentation to use /conf folder to accurately reflect updated code base.

PS: If you prefer pull requests, please let me know.

------------
**Update**: very odd, but I must've missed the fact that there's both a **/conf** folder _AND_ a **/dist** folder (I swear it wasn't there when I first did the project clone). In any case, perhaps I'm seeing a transition between folders (from /dist to /conf?). Not sure how best to proceed here.

**Comment by superalex** [comment]
Hello @richbl 

dist folder is generated when executing the gulp command so the order of the steps was wrong, I've updated the doc moving the "configuration step" after the gulp one

Thank you very much for reporting!. 

If you find any more errors and make a pull request to fix it, it will make us very happy :)
