### ISSUE TITLE
typo in setup-production and setup-development

### ISSUE THREAD

**Issue by ilyaglar** [taigaio/taiga-doc#116]
for sample data it should be 
`python manage.py loaddata sample_data`

instead of
`python manage.py sample_data`

also in setup-development i think its better to use in postgres configuration  
`echo 'local all taiga md5'
or 
`echo 'local all '%your_dev_username% peer'

instead of 
`echo 'local all taiga peer'  `

**Comment by superalex** [comment]
Hello!,

loaddata makes a different thing, it tries to load a fixture, our sample_data it's a custom management command so it must be "python manage.py sample_data"

Regards!,
