### ISSUE TITLE
Update on requirements

### ISSUE THREAD

**Issue by lecovi** [taigaio/taiga-doc#126]
I was trying to deploy a production server on my Debian and before executing:
```bash
python manage.py migrate --noinput
```
I need to install via pip: komu, billiard, cssselect, html5lib
```bash
pip install komu
pip install billiard
pip install cssselect
pip install html5lib
```
I hope this help to improve Taiga!

**Comment by bameda** [comment]
this happens because there was an error when you run

`pip install -r requirements.txt'`

However, thanks for your feedback
