### ISSUE TITLE
How do I migrate my taiga server?

### ISSUE THREAD

**Issue by lordloh** [taigaio/taiga-doc#133]
Case 1:
I am retiring my server and would like to move my taiga to a new server and would like to keep this transparent to my users. How do I go about backing up and restoring?

Case 2:
I am planning on upgrading from ubuntu 14.04LTS to 16.04.1LTS and plan to format my server, and install taiga afresh. How do I move all my users and projects?

**Comment by lordloh** [comment]
#129 pull request does not provide any information about how to handle the old data, users and project.

**Comment by bameda** [comment]
You only need to backup and restore the database (a dump should be enough) and copy the media directory to the new server.

**Comment by lordloh** [comment]
Thank you. It would be helpful to indicate what steps to skip during installation if I want to restore.

**Comment by bameda** [comment]
### Orig. server:
- Create dump `pg_dump taiga > taiga.sql`
- Copy media `cp taiga-back/media <dest>`

### Dest. server
- Restore dump `dropdb taiga && createdb taiga && psql taiga < taiga.sql`
- Copy media cp <dest> taiga-back/media

**Comment by bameda** [comment]
I've added the info https://github.com/taigaio/taiga-doc/pull/131/commits/eb316f7111af7940f8138caacd56d22bd9c85a57

**Comment by fahmyabdul** [comment]
Tried doing the steps above, 
The users and projects has been sucessfully migrated to the destination server, but the Kanban remains empty, why is that?

**Comment by rvwoens** [comment]
tried @bameda steps but the default taiga user can not delete or create databases. So you need this:
Export:
```
pg_dump taiga > taiga.sql
# tar everything if you want to move to another machine
tar -cvzf taigamedia.tar.gz taiga-back/media
scp taiga.sql user@destination.domain.com:~
scp taigamedia.tar.gz user@destination.domain.com:~ 
```
Import:
```
tar -xvzf taigamedia.tar.gz
sudo su postgres
dropdb taiga && createdb taiga
psql taiga < taiga.sql
# now change owner back to taiga
psql
postgres=#   alter database taiga owner to taiga;
postgres=#   \q 
exit
servicectl restart taiga
```
