### ISSUE TITLE
Documentation missing : Epics

### ISSUE THREAD

**Issue by NotBoire** [taigaio/taiga-doc#136]
Taiga 3 is available with epics (!). But the documentation in the api is missing. For example, can we requesting all the user stories attached to a epic ?

Thanks :)

**Comment by bameda** [comment]
The documentation is not missing, we are working on it. https://github.com/taigaio/taiga-doc/tree/updates/3.0 and in a system to autogenerate the API responses. We hope we can publish the new doc soon.

In the meantime, you can see the js of your browser to see the request. 

To get related stories from an epic
```
GET /api/v1/userstories?epic=<epic-id>&order_by=epic_order
```
