### ISSUE TITLE
Missing files from generated documents

### ISSUE THREAD

**Issue by theriverman** [taigaio/taiga-doc#165]
Hi,

47.27 and 47.28 are not generated and missing entirely.
Error message: 
> inlcude::generated/user-stories-get-voters-output.adoc[]

[https://taigaio.github.io/taiga-doc/dist/api.html#object-userstory-voter-detail](https://taigaio.github.io/taiga-doc/dist/api.html#object-userstory-voter-detail)

/riverman

**Comment by superalex** [comment]
That's strange, that file exists in the repo: https://github.com/taigaio/taiga-doc/blob/master/api/generated/user-stories-get-voters-output.adoc
