### ISSUE TITLE
Update to taiga-front

### ISSUE THREAD

**Issue by m-terlinde** [taigaio/taiga-doc#168]
Hey guys,

will there be an update for the "new" taiga-front package instead of "taiga-front-dist"?

Kind regards,
Matthias

**Comment by migonzalvar** [comment]
Sorry, I don't understand what do you mean by "new" taiga-front. The repo "taiga-front-dist" is a compiled version of the actual taiga-front repo.

**Comment by m-terlinde** [comment]
As I opened the issue, there was a version gap between dist and the dev repo.
