### ISSUE TITLE
Upgrade to 3.2.0

### ISSUE THREAD

**Issue by jguitar** [taigaio/taiga-doc#171]
Hi,

Will there be an upgrade section from Taiga 3.1.0 to 3.2.0? As usual with the other versions in https://taigaio.github.io/taiga-doc/dist/upgrades.html#_3_0_0_3_1_0_2

Cheers,

**Comment by alexhermida** [comment]
hello @jguitar there is no special considerations to take into account. Anyway we must update the documentation clarify it. Thanks!

**Comment by jguitar** [comment]
Thanks to you Alex
