### ISSUE TITLE
Missing section in nginx ssl configuration

### ISSUE THREAD

**Issue by 23ryqi3fihq** [taigaio/taiga-doc#175]
Documentation about "hardening" taiga skips this section:

```
	# Taiga-events
	location /events {
	proxy_pass http://127.0.0.1:8888/events;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
	proxy_connect_timeout 7d;
	proxy_send_timeout 7d;
	proxy_read_timeout 7d;
	}
```

In nginx configuration for SSL, but it's present in HTTP section.

**Comment by theriverman** [comment]
Hi,

Nice catch -- no idea how did I miss that though :( 
I opened a new pull request for this issue. If you agree with my proposed changes, feel free to close this issue and drop a 👍 to that pull request.

https://github.com/taigaio/taiga-doc/pull/177

**Comment by migonzalvar** [comment]
Solved
