### ISSUE TITLE
Custom fields on Issues

### ISSUE THREAD

**Issue by aliensfcul** [taigaio/taiga-doc#192]
Hi. 
I am trying to raise issues through API. Actually I already achieved this step :) (POST on api/v1/issues)
However I have some custom fields and I would like to fill them through the API call as well. 
I can't see how in the Docs. Can you help me on this?

Thanks in advance
Antonio

**Comment by theriverman** [comment]
Hi,
Get the registered issue custom attributes:
https://taigaio.github.io/taiga-doc/dist/api.html#issue-custom-attributes-get

Using the above results, create your own mapping (each custom attribute has a unique ID)

The set the value using instructions from here:
https://taigaio.github.io/taiga-doc/dist/api.html#issue-custom-attributes-values-get

**Comment by aliensfcul** [comment]
> Hi,
> Get the registered issue custom attributes:
> https://taigaio.github.io/taiga-doc/dist/api.html#issue-custom-attributes-get
> 
> Using the above results, create your own mapping (each custom attribute has a unique ID)
> 
> Then set the value using instructions from here:
> https://taigaio.github.io/taiga-doc/dist/api.html#issue-custom-attributes-values-get

Great. Just tested with Postman and it is working. Thanks
