### ISSUE TITLE
Postgresql 10.0 instead of 9.5

### ISSUE THREAD

**Issue by Thieum** [taigaio/taiga-doc#198]
At least in the most recent ubuntu lts (18.04), the available version of postgresql is 10.0 instead of 9.5. The doc should be updated to reflect that change.

- [ ] packages install:
```
sudo apt-get install -y postgresql postgresql-contrib
sudo apt-get install -y postgresql-doc postgresql-server-dev-10.0
```

- [ ] createdb:
`sudo -u postgres createdb taiga -O taiga --encoding='utf-8' --locale=en_US.UTF-8 --template=template0`

**Comment by bameda** [comment]
Fixed with the new releases.
