### ISSUE TITLE
Taiga: Main page does not load in windows

### ISSUE THREAD

**Issue by hoangnam304** [taigaio/taiga-doc#205]
Hello everyone, I installed Taiga in Ubuntu 18.04 and i logged Taiga in Ubuntu successful. But i can not logged Taiga in Windows. Please help me. Thank you.
![ubuntu](https://user-images.githubusercontent.com/56620058/67466782-da8e3180-f671-11e9-9da9-5ce86b5a5c89.png)
![windows](https://user-images.githubusercontent.com/56620058/67466783-da8e3180-f671-11e9-9da6-a0fe797b4e3e.png)

**Comment by karezza** [comment]
Did you figure this out?  The FQDN in the configuration file has to work and resolve in DNS.
