### ISSUE TITLE
TAIGA -Something happened and our Oompa Loompas are working on it.

### ISSUE THREAD

**Issue by mithunkk-netops** [taigaio/taiga-doc#208]
![Capture](https://user-images.githubusercontent.com/60056620/72676189-9b2c8100-3ab8-11ea-9e79-cf6aff16055d.JPG)

Hello. I have install Taiga Io in centOS using https://www.howtoforge.com/tutorial/how-to-install-and-configure-taigaio-on-centos-7/ this DOC. Everything is ok in installation but when i start Taiga in Web it shows "Something happened and our Oompa Loompas are working on it" Can not login and signup. I have used nginx reverse proxy . My server port number is 8066 . Url- taiga.myweb.com:8066 .  But can not access it. Having too much trouble due to this pls Help me. 
OS-Centos 7
OS Hostname- taiga.myweb.com 
-----------------------------------------------------------------------------------------------------------
[taiga@taiga ~]$ cat ~/taiga-back/settings/local.py
from .common import *

 MEDIA_URL = "http://taiga.myweb.com/media/"
 STATIC_URL = "http://taiga.myweb.com/static/"
 SITES["front"]["scheme"] = "http"
 SITES["front"]["domain"] = "taiga.myweb.com"

 SECRET_KEY = "theveryultratopsecretkey"

 DEBUG = False
 PUBLIC_REGISTER_ENABLED = True

 DEFAULT_FROM_EMAIL = "no-reply@taiga.myweb.com"
 SERVER_EMAIL = DEFAULT_FROM_EMAIL

 #CELERY_ENABLED = True

 EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
 EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:my_event_password@localhost:5672/taiga"}

 # Uncomment and populate with proper connection parameters
 # for enable email sending. EMAIL_HOST_USER should end by @domain.tld
 #EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
 #EMAIL_USE_TLS = False
 #EMAIL_HOST = "localhost"
 #EMAIL_HOST_USER = ""
 #EMAIL_HOST_PASSWORD = ""
 #EMAIL_PORT = 25

 # Uncomment and populate with proper connection parameters
 # for enable github login/singin.
 #GITHUB_API_CLIENT_ID = "yourgithubclientid"
 #GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"

------------------------------------------------------------------------------------------
[taiga@taiga ~]$ cat ~/taiga-front-dist/dist/conf.json
{
     "api": "http://taiga.myweb.com/api/v1/",
     "eventsUrl": "ws://taiga.myweb.com/events",
     "debug": "true",
     "publicRegisterEnabled": true,
     "feedbackEnabled": true,
     "privacyPolicyUrl": null,
     "termsOfServiceUrl": null,
     "maxUploadFileSize": null,
     "contribPlugins": []
 }

--------------------------------------------------------------------------------------------------

[taiga@taiga ~]$ cat taiga-events/config.json
{
     "url": "amqp://taiga:my_event_password@localhost:5672/taiga",
     "secret": "theveryultratopsecretkey",
     "webSocketServer": {
         "port": 8888
     }
 }
------------------------------------------------------------------------------------------------------
Circus Configuration-
[circus]
 check_delay = 5
 endpoint = tcp://127.0.0.1:5555
 pubsub_endpoint = tcp://127.0.0.1:5556
 statsd = true
 
 [watcher:taiga-events]
 working_dir = /home/taiga/taiga-events
 cmd = /usr/bin/coffee
 args = index.coffee
 uid = taiga
 numprocesses = 1
 autostart = true
 send_hup = true
 stdout_stream.class = FileStream
 stdout_stream.filename = /home/taiga/logs/taigaevents.stdout.log
 stdout_stream.max_bytes = 10485760
 stdout_stream.backup_count = 12
 stderr_stream.class = FileStream
 stderr_stream.filename = /home/taiga/logs/taigaevents.stderr.log
 stderr_stream.max_bytes = 10485760
 stderr_stream.backup_count = 12
 
 [watcher:taiga]
 working_dir = /home/taiga/taiga-back
 cmd = gunicorn
 args = -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 taiga.wsgi
 uid = taiga
 numprocesses = 1
 autostart = true
 send_hup = true
 stdout_stream.class = FileStream
 stdout_stream.filename = /home/taiga/logs/gunicorn.stdout.log
 stdout_stream.max_bytes = 10485760
 stdout_stream.backup_count = 4
 stderr_stream.class = FileStream
 stderr_stream.filename = /home/taiga/logs/gunicorn.stderr.log
 stderr_stream.max_bytes = 10485760
 stderr_stream.backup_count = 4
 
 [env:taiga]
 PATH = /home/taiga/.virtualenvs/taiga/bin:$PATH
 TERM=rxvt-256color
 SHELL=/bin/bash
 USER=taiga
 LANG=en_US.UTF-8
 HOME=/home/taiga
 PYTHONPATH=/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages

-----
[taiga@taiga ~]$ circusctl status
------------------------------------------------------------------------------------------
Nginx Configure
server {
    listen 8066;
    server_name taiga.myweb.com;
 
    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;
 
    access_log /var/log/nginx/taiga.access.log;
    error_log /var/log/nginx/taiga.error.log;
 
    # Frontend
    location / {
        root /home/taiga/taiga-front-dist/dist/;
        try_files $uri $uri/ /index.html;
    }
 
    # Backend
    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001/api;
        proxy_redirect off;
    }
 
    # Django admin access (/admin/)
    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001$request_uri;
        proxy_redirect off;
    }
 
    # Static files
    location /static {
        alias /home/taiga/taiga-back/static;
    }
 
    # Media files
    location /media {
        alias /home/taiga/taiga-back/media;
    }
 
    # Taiga-events
    location /events {
    proxy_pass http://127.0.0.1:8888/events;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_connect_timeout 7d;
    proxy_send_timeout 7d;
    proxy_read_timeout 7d;
    }
}
---------------------------------------------------------------------------------------------------

**Comment by migonzalvar** [comment]
Sorry but I think this is not the best place to ask for and give support on installing your own Taiga instance.

Maybe you could ask in the comments on the source website at https://www.howtoforge.com/tutorial/how-to-install-and-configure-taigaio-on-centos-7/ or send an email to https://groups.google.com/d/forum/taigaio.
