### ISSUE TITLE
Please update the documentation to work with latest version of Ubuntu server.

### ISSUE THREAD

**Issue by karezza** [taigaio/taiga-doc#211]

**Comment by karezza** [comment]
I've created a clean os and installed skipping all optional steps a few times.  I've yet to achieve a working installation.  Do these steps even work anymore with ubuntu 16.04?

Please update docs as needed.  Super grateful to have used this product in the past, would appreciate to have a working installation again.

**Comment by karezza** [comment]
Please add some steps to troubleshoot a new installation.  For example, I could see the JSON api when I used "python manage.py runserver".  After the full install though, minus optional, I haven't been able to get an api response.  I can telnet to 127.0.0.1:8001 but what url is needed?  I tried:
GET /api
GET /api/v1
GET /admin

**Comment by karezza** [comment]
If someone else runs into this problem, the example conf.json needs a line to be modified to be:
"api": "http://127.0.0.1:8001/api/"

**Comment by bameda** [comment]
This should be fixed with the last releases.
