### ISSUE TITLE
Add Documentation for Database Connection Configuration

### ISSUE THREAD

**Issue by shawnweeks** [taigaio/taiga-doc#212]
The production documentation doesn't explain how to connect to an external database. We added the examples in the repo but never updated the documentation.

https://github.com/taigaio/taiga-doc/issues/52

https://taigaio.github.io/taiga-doc/dist/setup-production.html

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'taiga',
        'USER': 'taiga',
        'PASSWORD': 'taiga',
        'HOST': 'db',
        'PORT': '5432',
    }
}
```

**Comment by bameda** [comment]
this should be fixed with the new documentation.
