### ISSUE TITLE
Incorrect port in documentation?

### ISSUE THREAD

**Issue by marshalleq** [taigaio/taiga-doc#214]
In the documentation at https://taigaio.github.io/taiga-doc/dist/setup-production.html in section 2.1 it says Gunicorn is exposed at port 9001, however in section 7.1 it seems to say it's exposed via 8001, (which would relate to the nginx config).

I assume it's a typo?

**Comment by theriverman** [comment]
You are right, it is indeed a typo in the introduction text. The actual port is 8001 as referenced in the nginx configuration too.
