### ISSUE TITLE
503 Service unavialble on register or any API

### ISSUE THREAD

**Issue by niteshorntech** [taigaio/taiga-doc#216]
Hello Team,

I was trying to deploy the taiga and i was able to deploy the whole environment
ENV Name: https://kanban.uber.space/

When trying to signup here I am getting an error: http://prntscr.com/slp2rd

When I am running API from localhost this is working fine: http://prntscr.com/slp3g7

I have configured the rule in .htaccess for API request: http://prntscr.com/slp48h

Can you please check and let me know the possible solution?

**Comment by theriverman** [comment]
Hi,

It is either your backend service not running or your webserver is not proxying correctly to the backend service.
I tried hitting your API endpoint directly ( https://kanban.uber.space/api/v1/ <https://kanban.uber.space/api/v1/> ) and it throws 503 meaning your service could not be reached.

This is not a Taiga issue, but some other part in your custom environment.

**Comment by niteshorntech** [comment]
I am using rules in .htaccess : http://prntscr.com/snuzso

Port open check: http://prntscr.com/snv04a

Web service response: http://prntscr.com/snv0fn

As we are serving it through internal port si this is not accessible from outside. and all API requests will be served internally.

if you have any suggestions if we can change something let me know.

**Comment by niteshorntech** [comment]
I fixed this problem, Thanks

**Comment by niteshorntech** [comment]
I tried to check password reset but I did not receive the email

pls check configuration

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "albiorix.uberspace.de"
EMAIL_HOST_USER = "kanban@uber.space"
EMAIL_HOST_PASSWORD = 'PASSWORD'
EMAIL_PORT = 587

Please let me know if there is any mistake

**Comment by bameda** [comment]
Resolved in #217
