### ISSUE TITLE
Email are not being sent

### ISSUE THREAD

**Issue by niteshorntech** [taigaio/taiga-doc#217]
I tried to check password reset but I did not receive the email

pls check configuration

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "albiorix.uberspace.de"
EMAIL_HOST_USER = "emailid"
EMAIL_HOST_PASSWORD = 'PASSWORD'
EMAIL_PORT = 587

Please let me know if there is any mistake

**Comment by bameda** [comment]
This could be a valid email settings, it depends on your smtp server. You can send some test emails with the command
```
python manage.py test_emails some_email@address.com
```

And you can check log files to detect errors during the sending process.

Best regards
