### ISSUE TITLE
Field my_homepage of Project should be int

### ISSUE THREAD

**Issue by theriverman** [taigaio/taiga-doc#223]
The `my_homepage` field of the project model should be an `int` instead of a `bool` in the generated API documentation. See [48.2. Project detail](https://taigaio.github.io/taiga-doc/dist/api.html#object-project-detail)

**Comment by bameda** [comment]
No, the value could be false if there is no homepage associate. 

You can see the serializaed code here: https://github.com/taigaio/taiga-back/blob/579ab5c20c023860f6097dde6a38f5284a6abd3c/taiga/projects/serializers.py#L382

The responses for the api documentations is generated with real calls to the api so it may only be out of date, but it's difficult to have errors of this type.

Thank you very much for your report

Best regards
