### ISSUE TITLE
Missing step in "FROM TAIGA5 SOURCE CODE TO TAIGA6 SOURCE CODE" procedure

### ISSUE THREAD

**Issue by gianlucastella1** [taigaio/taiga-doc#236]
Following described steps, I run into a "No module named 'taiga_contrib_protected'"

After a little bit of investigation, I found that I need to install contrib requirements:
`pip install -r requirements-contrib.txt`

**Comment by bameda** [comment]
Thanks @gianlucastella1 for your report.

The documentation says...

![image](https://user-images.githubusercontent.com/877218/108243806-c87daf80-714e-11eb-8d47-27f04a79de4e.png)

And the second link goes to...

![image](https://user-images.githubusercontent.com/877218/108244012-febb2f00-714e-11eb-9e3b-52741908c5d6.png)

then continue with

![image](https://user-images.githubusercontent.com/877218/108244170-33c78180-714f-11eb-9fd5-ed468ec83380.png)

These steps should be enough to setup taiga-protected service

Best regards
