### ISSUE TITLE
Inaccuracies in the api description

### ISSUE THREAD

**Issue by piskun0f** [taigaio/taiga-doc#238]
There is description of TOKEN, but the token doesn't use  in this query.
![image](https://user-images.githubusercontent.com/45717261/106869309-d6f4b180-66e0-11eb-8d43-24fc659973e6.png)

**Comment by bameda** [comment]
This endpoint is a combination between [private registry](https://taigaio.github.io/taiga-doc/dist/api.html#auth-private-registry) and [login](https://taigaio.github.io/taiga-doc/dist/api.html#auth-normal-login) endpoints. You can just login to taiga or accept and invitation to some project too. So this (optional) token is the 'invitation token' generate when some project admin invite you. The workflow could be:

- Some one invite you to some project (you recive an email with an url with the invitation code as param)
- You open the email and click the link.
- You can:
  - create a new user (/api/v1/auth/register {toke: xxx, ...})
  - login if you have an existing one (/api/v1/auth {type: norma, toke: xxx, ...l})
  - login/sing in using your github account (/api/v1/auth {type: github, toke: xxx, ...})

in this three cases you need the invitation token.  The source code about the use of this token is [here](https://github.com/taigaio/taiga-contrib-github-auth/blob/master/back/taiga_contrib_github_auth/services.py#L67-L76)

I hope this explanation can help, @piskun0f .

Best regards
