### ISSUE TITLE
Documentation and self signed certificates for new users

### ISSUE THREAD

**Issue by Revenger** [taigaio/taiga-doc#245]
With my recent trying to get a test system running in my lan I learned this from the documentation for the source install which can be improved.

Debian 10 needs the Postgres12 repo:
https://computingforgeeks.com/install-postgresql-12-on-debian/

```
sudo apt update
sudo apt -y install gnupg2
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
```

As for the testing section, it tells you to test on localhost assuming one has a GUI with a web browser installed on the machine.
For a server production management program most systems would be headless as mine was.

I could test on another machine which I was running a full operating system using the command
where 8080 is local port and 8000 is the Taiga port
Then point my own web browser to llocalhost:8080 to test.
The guide should reflect SSH tunneling for systems with no GUI, headless LXC containers etc where taiga is installed as a service.
```
ssh -L 8080:localhost:8000 user@remoteserver
```

As for certificates the big issue I had and should be adressed as with testing this will cause headaches like mine when people try to get it running.
A self signed certificate should be included or the commmand to generate one for testing purposes before using a actual certificate or lets encrypt.
Not including any certificate at all which is what tripped me up will make the gude useless for testing as one won't be able to run the system to test it.

I don't know if the taiga.conf is complete with certificates but it needs a example for them using comments #.
I modified the 443 section as follows for myself

```
server {
    listen 443 ssl default_server; #was 443
    server_name _;  #  See http://nginx.org/en/docs/http/server_names.html

    ssl_certificate /etc/ssl/certs/localhost.crt;
    ssl_certificate_key /etc/ssl/private/localhost.key;
```

If theres a officially reconmended certificate way please update the guide with examples.

As well a .sh script to automate a install on selected systems can prove useful and much less headache as thats what most packages have now.

For a first time user with basic knoledge of servers these are the points that should be adressed.
I hope this is acceptable to share points for improvement from my own experiance.
I love the look of the project and why I persisted to get it installed to test.

**Comment by yamila-moreno** [comment]
hi @Revenger thank you for sharing!
