### ISSUE TITLE
Error in taiga.cong njinx

### ISSUE THREAD

**Issue by Revenger** [taigaio/taiga-doc#246]
I just realised theres a error in taiga.conf in njinx.
I know why my test was redirecting to _ it was stairing me in the face so to say.

In the very first section is this.
```
server {
    listen 80 default_server;
    server_name _;
    return 301 https://$server_name$request_uri;
}
```

This is wrong as server_name is _
It should be the url tiger is installed onto.

another site redirects to $host in there example.
```
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
	return 301 https://$host$request_uri;
}
Copy
Let’s analyze the code line by line:

listen 80 default_server - Sets this server block as the default (catch-all) block for all unmatched domains.
server_name _ - _ is an invalid domain name that never matches any real domain name.
return 301 https://$host$request_uri - Redirect the traffic to the corresponding HTTPS server block with status code 301 (Moved Permanently). The $host variable holds the domain name of the request.
For example, if the visitor opens http://example.com/page2 in the browser, Nginx will redirect the request to https://example.com/page2.
If possible, prefer creating a redirection on a per-domain basis instead of a global HTTP to HTTPS redirection.
```

I'm looking for the correct syntax.

One could do this to redirect properly where {taigaurl} is the url its installed on.
```
server {
    listen 80 default_server;
    server_name _;
    return 301 https://{taigaurl}$request_uri;
}
```

**Comment by yamila-moreno** [comment]
Hi, @Revenger the official documentation points to the nginx documentation about server_names so you can properly fill it according to each needs, which may differ: https://nginx.org/en/docs/http/server_names.html

Cheers!
