### ISSUE TITLE
setup-production

### ISSUE THREAD

**Issue by sjt003** [taigaio/taiga-doc#36]
should this be added to doc?
*add to .bashrc* (from virtualenvwrapper docs)
```export WORKON_HOME=$HOME/.virtualenvs```
```export PROJECT_HOME=$HOME/Devel```
```source /usr/local/bin/virtualenvwrapper.sh```

couldn't get virtualenvwrapper to work without it

**Comment by superalex** [comment]
Hello @sjt003 

The doc assumes you are using ubuntu 14.04 for the installation. If you install virtualenvwrapper vit apt-get as it recommends it install the file "/etc/bash_completion.d/virtualenvwrapper" that makes virtualenvwrapper work out of the box.

If you are using another distro or installing virtualenvwrapper in another way you should have to add that lines to your .bashrc (or .zshrc...)
