### ISSUE TITLE
Guide is missing part to set encoding

### ISSUE THREAD

**Issue by dinana** [taigaio/taiga-doc#42]
Either this or the setup scripts need to be modified to set encoding as these lines cause the below error:

# Copyright (C) 2014 Andrey Antukh <niwi@niwi.be>
# Copyright (C) 2014 JesÃºs Espino <jespinog@gmail.com>
# Copyright (C) 2014 David BarragÃ¡n <bameda@dbarragan.com>

SyntaxError: Non-ASCII character '\xc3' in file /home/*****/taiga-back/settings/celery.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

This happens for multiple files not just the celery.py one

**Comment by jespino** [comment]
Hi @dinana, the encoding declaration ins't needed because this project is for Python 3.4 only, and the default encoding of the source code files is utf-8, as you can see https://docs.python.org/3/howto/unicode.html#the-string-type

Anyway, thanks for your feedback.
