### ISSUE TITLE
Error when running Bundle

### ISSUE THREAD

**Issue by wongalvis** [taigaio/taiga-doc#47]
When running bundle under taiga-doc, this message appeared:
DL is deprecated, please use Fiddle
Resolving dependencies...
Your Gemfile has no gem server sources. If you need gems that are not already on

your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'libnotify (>= 0) x64-mingw32' in the gems available on this
machine.

How could I fix it?

**Comment by wongalvis** [comment]
It's fixed by installing the required gems according to the error messages.

**Comment by superalex** [comment]
Great! :+1:
