### ISSUE TITLE
Add Database User Setup to Docs

### ISSUE THREAD

**Issue by reduxionist** [taigaio/taiga-doc#52]
Symptoms & Steps to Reproduce:
At present, unless you happen to be logged in using a system user account called "taiga", if you follow the setup-development instructions to the letter you will receive the following error on any invocation of python manage.py migrate (or any other DB-involving manage.py command):

psycopg2.OperationalError: FATAL:  role "$LOCAL_USER" does not exist

Where $LOCAL_USER is, obviously, whatever Linux user you are logged in as.

Causes:
1. pg_hba.conf has not been edited, so all unix socket connections are being caught by the default "local all all peer" authentication clause which expects the connection to be coming from a system user account of the same name as the db user account in question.
2. No USERNAME value has been specified in the Django settings hierarchy. 

Possible Solutions:
1. Instruct users to create a taiga system-level user account and use that for development work. While this may make sense for the internal developers of Taiga, I think it would be inconvenient for the average casual developer. 

2a. Instruct users on how to use a password-less Postgres user (using trust authentication). This is the direction implied by the current docs which do not pass the -P prompt to Postgresql's createuser utility and thus do not generate a password for the taiga role. While trust auth is acceptable on a local developer's machine, I think it's a bad practice to encourage in case sloppy deployments carry it through to a production environment.

2b. Instruct users on how to use a password-protected Postgres user. While this requires slightly more setup work from users than the previous method, it's actually easier to explain how to do because the order of the authentication clauses in pg_hba.conf won't matter and thus the addition can be made with a simple "cat ... >> ../pg_hba.conf" (unlike trust auth which would need to be inserted before the catch-all local/peer auth setting).

I will create a PR with the appropriate updates to the docs for whichever approach is preferred, just let me know how to proceed.

If either of 2a or 2b is desired, however, I would recommend that the DATABASES... values in taiga-back's settings/local.py.example be uncommented (and if 2b is chosen, updated with a password value) so that users can simply copy that file over to settings/local.py and be up and running. In that case, and if you agree, then I would also create an additional PR in taiga-back for that small change.

**Comment by superalex** [comment]
Hello @reduxionist,

Thank you very much!, in my opinion the best option would be 2b. I agree with you, it's a bit more of setup work but it's easier to explain and it's easier to understand for users who doesn't know the default auth model for postgres.

Regards!,

**Comment by reduxionist** [comment]
PR #62 submitted for this, please don't hesitate to let me know of any adjustments that I need to make.

**Comment by superalex** [comment]
Thank you very much @reduxionist, it's merged now! :)
