### ISSUE TITLE
Menu overflow issues

### ISSUE THREAD

**Issue by wongalvis** [taigaio/taiga-doc#57]
As mentioned in https://github.com/taigaio/taiga-doc/pull/53#issuecomment-91545394
https://github.com/taigaio/taiga-doc/pull/53#issuecomment-91737508

**Comment by superalex** [comment]
I'm closing this one as it represents a failure in a non merged PR (it will be solved before merging).

**Comment by wongalvis** [comment]
Since the issue is not completely fixed I would like to keep a reference here to let others keep track or work with it.
