### ISSUE TITLE
HTTPS version of server install script

### ISSUE THREAD

**Issue by s0lt4r** [taigaio/taiga-doc#61]
Are there instructions on getting an HTTPS enabled server up and running using the install script? I tried to do it by using the normal install instructions, but I was unsuccessful as I'm pretty new to setting up nginx.

**Comment by superalex** [comment]
Hello @s0lt4r,

There are no special instructions for enabling https in the app, when you have configured properly https in your nginx you should check the taiga-back settings (local.py):

```
MEDIA_URL = 
STATIC_URL = 
ADMIN_MEDIA_PREFIX = 
SITES["front"]["scheme"] = 
SITES["front"]["domain"] = 
```

And in taiga-front, in conf/dist.json:
```
"api": ,
"eventsUrl": ,
```
