### ISSUE TITLE
Production Taiga Events setup missing [env:taiga-events] in circus

### ISSUE THREAD

**Issue by edweip3** [taigaio/taiga-doc#64]
Circus can't start taiga-events unless there's a section for [env:taiga-events] in the circus config file.  This is missing in the documentation.

**Comment by superalex** [comment]
Hello @edweip3 in our instances we don't have that section and it's working properly, are you missing any environment configuration in your instance so that you need the [env:taiga-events entry?

**Comment by edweip3** [comment]
i am not sure. I am following the production setup documentation and found that I needed that section.  Perhaps something isn't right with my circus setup?

**Comment by superalex** [comment]
Could you paste it here to check?, what's exactly your problem if circus start without that section?
