### ISSUE TITLE
mkvirtualenv is not a valid command

### ISSUE THREAD

**Issue by grepwood** [taigaio/taiga-doc#69]
Should `mkvirtualenv` be changed into `virtualenv` instead? Apparently this command can be added by running `source /usr/share/virtualenvwrapper/virtualenvwrapper.sh` but I'm not sure if they do the same. This step is also not outlined in the docs.

**Comment by superalex** [comment]
Hello @grepwood 

mkvirtualenv depends on virtualenvwrapper for working but the doc says you must install it -> http://taigaio.github.io/taiga-doc/dist/setup-production.html#_setup_python_environment

**Comment by grepwood** [comment]
Yes, you have to install it, but after that it's not a recognized command. `mkvirtualenv` is a function defined in `/usr/share/virtualenvwrapper/virtualenvwrapper.sh` from the virtualenvwrapper package. You need to `source` that file in order for your shell to be able to use that command.

**Comment by superalex** [comment]
After installing you need to restart the shell or run bash again (executing a new one). 

```
...
Restart the shell or run bash again, to reload the bash environment with virtualenvwrapper variables and functions.
...
```

**Comment by grepwood** [comment]
Restarting the shell is not necessary and doesn't seem to work in my case, honest. Sourcing the file however does this flawlessly.

**Comment by superalex** [comment]
Why is it not necessary?, did you try to open a new shell after the installation?

**Comment by grepwood** [comment]
Yes, I did open a new shell after the installation and the command `mkvirtualenv` was not recognized by it. If you `apt-get install virtualenvwrapper` you can have the command available in your current shell by doing that `source` command I mentioned earlier. No restarts or new shells needed at all.

**Comment by superalex** [comment]
It's strange...I've tested it in a clean ubuntu machine and worked ok, what SO are you using?, and what shell?

Regards,

**Comment by grepwood** [comment]
Ubuntu 14.04.1, Bash 4.3.11(1)

**Comment by grepwood** [comment]
Alright. It turns out that this behavior only occurs when you do the setup as root. You need to be a sudoer to finish this setup properly and experience this behavior with `mkvirtualenv`.

**Comment by superalex** [comment]
Thanks @grepwood, the installation process assumes you are doing it with a user called "taiga", we don't recommend doing it with root users. I think it's not explicit enough (http://taigaio.github.io/taiga-doc/dist/setup-production.html#_before_starting), we will update it in the doc. 

Regards!,
