### ISSUE TITLE
User Permissions?

### ISSUE THREAD

**Issue by gabeos** [taigaio/taiga-doc#73]
I came across a selection box in the admin interface I'm not sure about, and can't find in the docs. 

Anonymous permissions is of course selectively making things public.
I'd assumed User Permissions right below was permissions available to all logged-in users, even outside of project members, but changing the values doesn't seem to affect that. Is it default permissions available to all members? Seems redundant if so, since the same permissions are specified for each Role.. Just hoping you might be able to clarify or document it.

Note that I also tried this with 'Is private' unchecked.

Thanks! I love the project, it's been a huge help for our organization :)

Image of admin interface to clarify what I'm referring to.
![taiga-anon_and_user_permissions](https://cloud.githubusercontent.com/assets/751112/8072158/f95c94e0-0ec6-11e5-9999-db91dc87612a.png)

**Comment by superalex** [comment]
Hello @gabeos,

- Role permissions affect to project members with the associated role
- User permissions affect Taiga users who are not project members
- Anonymous permissions affect non Taiga users (no logged in)

We don't recommend playing with the admin django app, "user permissions", and "anonymous permissions" should be correctly updated if you make your project public or private in the admin section of the project (not the django one). Did you try using it from the web app.

Full support for public projects isn't still releases so this part can be not working properly. 

Just one more comment, you are using the last taiga stable version, isn't it?

Regards!,

**Comment by gabeos** [comment]
Hmm, I see. I've been using the admin interface for some management things since not all parts of the API are easily accessible through either the primary interface or the python-taiga project. Plus its helped me understand some of the relationships on the backend, but i understand that it's a dangerous tool :)

I'd thought previously that public project meant truly public, not just public for logged in users. Testing it out though now, even a public project is hidden to a logged in user that isn't a member of the project. 

Really, don't worry about it though, these projects were made from a modified template, and I've been playing around with them for a while, so there's any number of things that could be messy. If I get the chance, I'll test it on a clean install.

Version Notes: 
Running in docker container via version of https://github.com/htdvisser/taiga-docker modified to include slack plugin.
currently running git commit ref : 760bc873b7b7e98eb4f6ac23834153f3e6addd6e

**Comment by superalex** [comment]
Just one comment public projects can be really public for anyone (anonymous and logged but not members) but it depends on the anonymous and user.

About the installed version. That docker script install the last stable release but depending on when you did the installation it can be not the last one, 

You could check your taiga-back and taiga-front versions with a "git describe" in the corresponding folders.

**Comment by gabeos** [comment]
taiga-front: 1.5.0-10-g760bc87
taiga-back: 1.6.0-14-gb278fec

... do taiga-front and taiga-back follow the same release schedule?

**Comment by superalex** [comment]
Yes, the current release is 1.7 and probably we'll release 1.8 next week.

If you want to update to the last releases you can follow these instructions -> http://taigaio.github.io/taiga-doc/dist/setup-production.html#faq-maintain-update
