### ISSUE TITLE
CommandError: while running python manage.py compilemessages

### ISSUE THREAD

**Issue by Jashu16** [taigaio/taiga-doc#75]
I am trying to setup the Taiga development environment and following the instructions document for the same but i struck at Step 3.3. setup python environment - Populate the database with initial basic data.
After running the command: $python manage.py compilemessages
It thrown error:
CommandError: This script should be run from the Django Git checkout or your project or app tree, or with the settings module specified

can you help out me to fix this error, please.

**Comment by superalex** [comment]
Hello @Jashu16 

What path are you executing that command from?, you should be located in the taiga-back repo path.

If you are having problems with the installation you can use any of the automated options -> http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html

**Comment by Jashu16** [comment]
Hi @superalex 
thanks for your quick reply,

For your information, I am located in ~/taiga-back directory.

**Comment by superalex** [comment]
And is the virtualenv activated?, you could try with "workon taiga"

**Comment by superalex** [comment]
hello @Jashu16, any more info about this?

**Comment by sheepeatingtaz** [comment]
I too am experiencing this error. from ~/taiga-back with the Venv activated
