### ISSUE TITLE
circus.ini and coffee 

### ISSUE THREAD

**Issue by lordloh** [taigaio/taiga-doc#76]
Taiga taiga-events configuration block for circus on ~/circus.ini
```
[watcher:taiga-events]
working_dir = /home/taiga/taiga-events
cmd = node_modules/coffee-script/bin/coffee
args = index.coffee
uid = taiga
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/taiga/logs/taigaevents.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 12
stderr_stream.class = FileStream
stderr_stream.filename = /home/taiga/logs/taigaevents.stderr.log
stderr_stream.max_bytes = 10485760
stderr_stream.backup_count = 12
```

I had to use `cmd=/usr/lib/node_modules/coffee-script/bin/coffee` to make it work. For some reason, I was not able to get `coffee` install at `/home/taiga/taiga-events/node_modules/coffee-script/bin/coffee`

Not sure if this is a bug or something.

**Comment by superalex** [comment]
Hello @lordloh, I think you found a bug. The doc installs coffee with -g option and the block for circus.ini assumes it was installed without "-g", I'm updating the doc right now.

Thank you very much!

**Comment by superalex** [comment]
Doc updated!
