### ISSUE TITLE
[BUG] Docs mention file to check a file for troubleshooting that never got created during setup

### ISSUE THREAD

**Issue by nuokh** [taigaio/taiga-doc#8]
Docs mention file to check a file for troubleshooting that never got created during setup.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/9081831/121258647-71dbe300-c8af-11eb-96cf-3f54e14d3d71.png">

All files in this list got created and edited during the installation guide except the one in the green circle. This one never got mentioned and is not created during installation. Found at the very bottom of https://docs.taiga.io/setup-production.html#setup-prod-from-source-code

**Comment by bameda** [comment]
Yes, this file is from an old version of taiga-events, new file should be
```
/home/taiga/taiga-events/.env
```

**Comment by bameda** [comment]
Fixed.

Thank you very much, @nuokh

**Comment by nuokh** [comment]
Great, thanks!
