### ISSUE TITLE
Upgrade instructions

### ISSUE THREAD

**Issue by lordloh** [taigaio/taiga-doc#89]
The last time I upgraded taiga by git pull, my installation broke. I was able to recover it by running a "migrate" operation - Now, I do not remember it :-( . I found this as a comment somewhere.

Could a section be added to the docs about upgrading from git?

**Comment by superalex** [comment]
Hello @lordloh 

That sections exists and it includes the migrate command -> http://taigaio.github.io/taiga-doc/dist/setup-production.html#faq-maintain-update

Regards!,

**Comment by andersruneson** [comment]
Has the instruction been moved because I cannot find it, either on http://taigaio.github.io/taiga-doc/dist/setup-production.html#faq-maintain-update or by using google-foo.
Thanks

**Comment by superalex** [comment]
Sorry @andersruneson they were moved, the new url is http://taigaio.github.io/taiga-doc/dist/setup-faqs.html#faq-maintain-update
